name: perl
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
jobs:
macos-latest:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: shogo82148/actions-setup-perl@v1
      - uses: perl-actions/install-with-cpanm@v1
        with:
          args: -n --installdeps .
      - run: perl -V
      - name: Run tests
        run: prove -l t xt
windows-latest:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: shogo82148/actions-setup-perl@v1
        with:
          distribution: strawberry # ignored non-windows
      - uses: perl-actions/install-with-cpanm@v1
        with:
          args: -n --installdeps .
      - run: perl -V
      - name: Run tests
        run: prove -l -j4 t
